/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package discord.bot.kotlin

import discord.bot.kotlin.application.impl.ComputeEngineServiceImpl

fun main(args: Array<String>) {
  ComputeEngineServiceImpl().startInstance()
}
