/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package discord.bot.kotlin

import discord.bot.kotlin.application.impl.ComputeEngineServiceImpl

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
//    println(App().greeting)
    ComputeEngineServiceImpl().startInstance()
}
